@isTest
public class DocuSignAPI_statusTest{

    public static testMethod void testDocuSignAPI_status1() {
    
        new DocuSignAPI_status.VoidEnvelope_element();
        new DocuSignAPI_status.ArrayOfCustomField();
        new DocuSignAPI_status.SSN9Information(); 
        new DocuSignAPI_status.Attachment(); 
        new DocuSignAPI_status.FormDataXfdfField();
        new DocuSignAPI_status.ArrayOfAttachment();
        new DocuSignAPI_status.DocumentStatus(); 
        new DocuSignAPI_status.ArrayOfDocumentPDF(); 
        new DocuSignAPI_status.EnvelopeAuditEventsResult_element(); 
        new DocuSignAPI_status.SynchEnvelopeResponse_element(); 
        new DocuSignAPI_status.EnvelopeStatusFilter(); 
        new DocuSignAPI_status.EnvelopeStatus();
        new DocuSignAPI_status.CustomField();
        new DocuSignAPI_status.DocumentPDF();
        new DocuSignAPI_status.DocuSignEnvelopeInformation(); 
        new DocuSignAPI_status.SynchEnvelope_element();  
        new DocuSignAPI_status.EnvelopeAuditEvents_element(); 
        new DocuSignAPI_status.FormDataXfdf(); 
        new DocuSignAPI_status.ArrayOfTabStatus(); 
        new DocuSignAPI_status.VoidEnvelopeResponse_element(); 
        new DocuSignAPI_status.RequestStatusesResponse_element(); 
        new DocuSignAPI_status.GetStatusInDocuSignConnectFormatResponse_element(); 
        new DocuSignAPI_status.RequestStatusExResponse_element();
        new DocuSignAPI_status.DOBInformation();
        new DocuSignAPI_status.GetStatusInDocuSignConnectFormat_element();
        new DocuSignAPI_status.ArrayOfString1();
        new DocuSignAPI_status.ArrayOfString2(); 
        new DocuSignAPI_status.ArrayOfDocumentStatus();
        new DocuSignAPI_status.AuthenticationStatus();
        new DocuSignAPI_status.ArrayOfEnvelopeStatusCode();
        new DocuSignAPI_status.SynchEnvelopeStatus(); 
        new DocuSignAPI_status.Ping_element();
        new DocuSignAPI_status.RequestStatusEx_element(); 
        new DocuSignAPI_status.IDCheckInformation(); 
        new DocuSignAPI_status.RecipientStatus(); 
        new DocuSignAPI_status.RequestStatus_element(); 
        new DocuSignAPI_status.RequestStatusResponse_element(); 
        new DocuSignAPI_status.RequestStatusesExResponse_element(); 
        new DocuSignAPI_status.FormData(); 
        new DocuSignAPI_status.PingResponse_element(); 
        new DocuSignAPI_status.EnvelopeStatusFilterBeginDateTime();
        new DocuSignAPI_status.RequestStatuses_element(); 
        new DocuSignAPI_status.TabStatus();
        new DocuSignAPI_status.FilteredEnvelopeStatuses(); 
        new DocuSignAPI_status.ArrayOfRecipientStatus(); 
        new DocuSignAPI_status.AddressInformation();
        new DocuSignAPI_status.EnvelopeAuditEventsResponse_element(); 
        new DocuSignAPI_status.VaultingDetails(); 
        new DocuSignAPI_status.UserInfo(); 
        new DocuSignAPI_status.VoidEnvelopeStatus(); 
       
   }
   
 }